main:
  seed: 0 # type=int, default=0 - Leave 0 - seed will be chosen depending on run_id
  use_gpu: true

  frames: 2.e+6 # Number of frames of training (procs number of frames / step are processed)

  log_interval: 1 # Number of training steps between two logs (default: 1)")
  save_interval: 10 # Number of training steps between two saves
  plot: False # log & plot into Wandb
  plot_x_axis: "frames"  # x axis source for plotting logs (e.g. vs update step)
  stats_window_size: 64   #
  save_best: False # Save separately best model
  save_all: False # Save separate model for each save_interval

env_cfg:  # Example of envs cfg -
  env: BlockMolEnvGraph-v1 # Env name
  procs: 16 # Number of parallel environments to run
  actual_procs: 8 # Actual number of CPU threads to distribute the environments
  wrapper:  #  List of wrappers - applied in reverse order
  env_args:
    reward: "DummyReward"
    random_steps: 3
    max_steps: 7
    allow_removal: True
#    seed_cnt: 50
    env_seed: 3
    pre_saved_graph: True

eval_env_cfg:  # Example of envs cfg -
  env: BlockMolEnvGraph-v1 # Env name
  procs: 1 # Number of parallel environments to run
  actual_procs: 1 # Actual number of CPU threads to distribute the environments
  eval_mode: True
  env_args:
    reward: "PredockedReward"
    env_seed: [13, 14, 15]
    eval_mode: True

proxy_dock: /scratch/andrein/lz2/results/2021Jun05-125747_breg/0001_dataset.weighted_sampler_False/0/best_model.pk
algo: ppo
log_interval: 1
save_interval: 10000
eval_interval: 0
eval_episodes: 32
eval_eps: 0.05
repeat_eval_eps: 1
eval_determinitistic: False
log_monitor: False

num_env_steps: 30.0e+7
no_cuda: False
offset: 0
use_wandb: True
name: ""
cuda_deterministic: False

seed: 0

num_steps: 256
ppo_epoch: 4
num_mini_batch: 32

use_linear_lr_decay: true
lr: 2.5e-4
eps: 1.0e-05
alpha: 0.99
gamma: 0.99
use_gae: True
gae_lambda: 0.95
entropy_coef: 0.08
value_loss_coef: 0.5
max_grad_norm: 0.5
clip_param: 0.1

use_proper_time_limits: False

policy:
  sample_best: False

model:
  name: MPNNextra # EGNNetRLBO #MPNNet_v2  # MPNNetMultihead
  recurrent: False
  dim: 128
  use_init: True
##  levels: 6
#  dim: 256
#  m_dim: 256
#
gail: False
gail_batch_size: 128
gail_epoch: 5

