cuda: True
seed: 0
project_name: cond
use_wandb: True
classification: True
max_steps: 8
cond_steps: False
debug: False
online_dataset: True
online_dataset_collect_freq: 1
weight_step: True
weight_dock: True
weight_end: True
loss_agg: "mean"

dataset_cfg:
  filter_candidates: True
  qed_th: 0.3
  synth_th: 4.
  sample_size: 0 # 0
  mol_graph_pool: 40
  online_batch_size: 4000
  online_max_traj: 250000
  online_start_traj: 50000 # 50000
  test_set_size: 100
  test_set_samples: 30

env_seed: 123

batch_size: 1024
train_split: 0.8
num_epochs: 5000
eval_freq: 1000 # 25
test_freq: 1 # 25
log_freq: 1
lr: 0.00025


#model:
#  name: MPNNcond # MPNNcond # SGC # TriangSag # MPNNet # MPNNet_v2 # MPNNet
#  num_feat: 14
#  num_out: 2
#  levels: 12


model:
  name: DeeperGCNSteps # MPNNcondTestSet # MPNNcond # SGC # TriangSag # MPNNet # MPNNet_v2 # MPNNet
  num_feat: 14
  num_out: 2
#  levels: 12
  conditioning: [["r_steps", 10], ["rcond", 1]]
  cond_level: 20
  dropout: 0
  dim: 128
