name: lz

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.6.*
  - sphinx
  - pip
  - cudatoolkit=10.1.*
  - tensorflow-gpu
  - tensorboardX
  - pytorch==1.7.0
  - torchvision
  - rdkit
  - pandas
  - networkx
  - scikit-image
  - numba
  - isodate
  - jsonschema
  - redis-py=3.5.*
  - pyyaml
  - colorama
  - filelock
  - aiohttp
  - beautifulsoup4
  - future
  - lz4
  - tabulate
  - fastparquet
  - boto3
  - pytest
  - pytest-cov
  - pyarrow
  - mlflow
  - tqdm
  - cloudpickle=1.3.*
  - py-opencv
  - joblib
  - msgpack-python=0.6.*
  - plyfile
  - psutil
  - pymongo
  - rdflib
  - scikit-learn
  - threadpoolctl
  - pip:
    - -f https://pytorch-geometric.com/whl/torch-1.7.0.html
    - torch-scatter==latest+cu101
    - torch-sparse==latest+cu101
    - torch-cluster==latest+cu101
    - torch-spline-conv==latest+cu101
    - ray==1.1
    - orion
    - wandb
    - torch-geometric
    - ray[rllib]
    - git+https://github.com/chemprop/chemprop.git#egg=chemprop
    - typed-argument-parser
    - gym
    - dm-tree
    - sphinx-rtd-theme
    - recommonmark
