cuda: True
seed: 0
project_name: cond
use_wandb: True
classification: True
max_steps: 8
cond_steps: False
debug: False
online_dataset: True
online_dataset_collect_freq: 1

dataset_cfg:
  filter_candidates: True
  qed_th: 0.3
  synth_th: 4.
  sample_size: 0
  mol_graph_pool: 40
  online_batch_size: 4000
  online_max_traj: 300000
  online_start_traj: 10000

env_seed: 123

batch_size: 1024
train_split: 0.8
num_epochs: 5000
eval_freq: 25
log_freq: 1
lr: 0.00045


#model:
#  name: MPNNcond # MPNNcond # SGC # TriangSag # MPNNet # MPNNet_v2 # MPNNet
#  num_feat: 14
#  num_out: 2
#  levels: 12


model:
  name: DeeperGCNSteps # MPNNcond # SGC # TriangSag # MPNNet # MPNNet_v2 # MPNNet
  num_feat: 14
  num_out: 2
#  levels: 12
  conditioning: [["r_steps", 10], ["rcond", 1]]
  cond_level: 20
  dropout: 0
