name: py37_bayesvs
channels:
  - rdkit
  - pytorch
  - soumith
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - pytorch=1.4
  - torchvision=0.5
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - pip
  - rdkit=2020.03.1.0
  - scipy=1.1.0
  - scikit-learn=0.22
  - jupyterlab
  - pytest
  - pip:
    - corner
    - lazy
    - tqdm
    - tabulate


