cuda: True
seed: 0
project_name: lzreg
use_wandb: True
eval_freq: 10 # TODO 10

optim:
  optim: RAdam # RAdam #RAdam
  optim_args:
    lr: 1.e-3 # 2.5e-4 # 1.e-3
#    momentum: 0.9
  #    betas: [0.9, 0.999]
#  lr_sheduler: ReduceLROnPlateau
  train_epochs: 1000 # TODO 1000
  batch_size: 32 # TODO 32
  batch_gradient: 1 # TODO 1
  epoch_size: 50000
  classification: &classification True

dataset:
  num_workers: 12
  max_mol: 0 # TODO 0
  train_split: [0.8, 0.2]
  seed_split: 123
  transform_complete: False # TODO True
  eval_quant: [0.01, 0.09, 0.20] # actual: eval_quant + [1-sum(eval_quant)*2] + eval_quant[::-1]
  weighted_sampler: True # If classification, than it will be equal from the two classes
  weighted_sampler_cbins: 100 # The less, the more values are groupped in same bing. same prob sampling for bins of 1.
  clip_stds: 10
  positive_quantile: 0.1 # In case of classification we consider top (positive_quantile*100)% scores


model:
  name: TriangSag # TriangSag # MPNNet # MPNNet_v2 # MPNNet
  num_feat: 14
  classification: *classification