model:
  name: ["MPNNet", "MPNNet_v2", "EGNNetRLBO", 'AGNN', 'Arma', 'AttFP', 'CoraNet', 'DGCNN', 'DNA', 'Faust', 'FILM', 'GAT', 'GAT2', 'GCN', 'GeniePathLazy', 'GeniePath', 'Saint', 'GUnet', 'MutagGin', 'DeeperGCN', 'PNA', 'PPINet', 'ProtMincutPool', 'SAGE', 'DGCNNSeal', 'SGC', 'SuperGat', 'TaGCN', 'TriangSag']
  dropout: [0]
  dim: [128]
dataset_cfg:
  dataset_score_candidates: [True, False]
