#!/bin/bash
#SBATCH --array=1-33
#SBATCH --account=rrg-bengioy-ad #def-dprecup  #def-bengioy  # rrg-bengioy-ad
#SBATCH -o /scratch/andrein/Lambda/slurm-%j.out
#SBATCH --cpus-per-task=18                   # Ask for 2 CPUs
#SBATCH --gres=gpu:1                          # Ask for 1 GPU
#SBATCH --mem=44Gb                             # Ask for 10 GB of RAM
#SBATCH --time=12:00:00                        # The job will run for 3 hours

source $HOME/.bashrc

module load StdEnv/2018.3
module load python/3.7 cuda/10.1 cudnn/7.6.5
module load nixpkgs/16.09
module load gcc/7.3.0
module load rdkit/2019.03.4
module load openbabel/2.4.1
export PATH=$CUDA_PATH/bin${PATH:+:${PATH}}
#export PATH=/lustre03/project/6004852/mkkr/Programs/mgltools_x86_64Linux2_1.5.6/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_PATH/lib64
export LIBRARY_PATH=$LIBRARY_PATH:$CUDA_PATH/lib64
#export PATH=/lustre03/project/6004852/mkkr/Programs/mgltools_x86_64Linux2_1.5.6/bin${PATH:+:${PATH}}
module load python/3.7 cuda/10.1 cudnn/7.6.5
module load httpproxy

source /home/andrein/miniconda/etc/profile.d/conda.sh
conda activate alz7
source deactivate
source activate alz7
conda activate alz7

# PYTHONPATH to the modified version of the repository
export PYTHONPATH="${PYTHONPATH}:/home/andrein/r2gflow"


WANDB_DISABLE_CODE=true

echo "Runnig sbatch array job $SLURM_ARRAY_TASK_ID"
echo "Running sbatch job $SLURM_ARRAY_JOB_ID"

# Here is the folder path generated by the liftoff-prepare command
rel_path="/scratch/andrein/gflow/results/folder_with_many_configs"

# Here liftoff will look for 1 sub-experiment that hasn't started (no .__start .__end or .__crash) and run it
liftoff LambdaZero/examples/gflow/train.py --max-runs 1 --no-detach ${rel_path}
