name: test package
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - train-reward-model

jobs:
  build:

    name: tests
    runs-on: ubuntu-latest

    steps:
    - name: checkout code 
      uses: actions/checkout@v1
    - name: create Conda environment 
      run: |
          ./install-cpu.sh lz
    - name: activate and setup environment, then test
      run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          echo "### activate environment"
          conda activate lz
          echo "### run setup develop"
          python setup.py develop
          echo "### see what the environment is composed of"
          pip freeze
          echo "### running tests"
          pytest LambdaZero/datasets/brutal_dock/tests/ # need a better way of ignoring non-pytest file with "test" in their name.
