name: test package
# This workflow is triggered on pushes to the repository.
# 
# It is possible to start an interactive ssh session using the command:
#    - name: Setup tmate session
#      uses: mxschmitt/action-tmate@v2

on:
  push:
    branches:
      - '*'

jobs:
  build:

    name: tests
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: create the conda environment
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: false
        python-version: 3.6
        activate-environment: lz
        environment-file: environment-linux.yml
        auto-activate-base: false

    - name: setup environment
      shell: bash -l {0}
      run: python setup.py develop

    - name: run tests
      shell: bash -l {0}
      run: pytest
