name: test install-prog-data.sh 
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:

    name: install programs and test
    strategy:
        matrix:
            os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout code 
      uses: actions/checkout@v2

    - name: create Conda environment (mac)
      run: conda env create -f environment-mac.yml
      if: matrix.os == 'macos-latest'

    - name: create Conda environment (linux)
      run: conda env create -f environment-linux.yml
      if: matrix.os == 'ubuntu-latest'

    - name: activate and setup environment, install programs, and then test
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        echo "### activate environment"
        conda activate lz
        echo "### run setup develop"
        python setup.py develop
        echo "### run install-prog-data.sh"
        bash install-prog-data.sh -d $HOME/datasets/ -p $HOME/programs/ -s $HOME/summaries/
        echo "### running tests including external programs"
        pytest --external_program
