name: test install-prog-data.sh 

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - master

jobs:
  build:

    name: tests
    strategy:
        matrix:
            os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout code 
      uses: actions/checkout@v2
    - name: execute install-prog-data.sh
      run: |
          bash install-prog-data.sh -d $HOME/datasets/ -p $HOME/programs/ -s $HOME/summaries/
